name: Build

on:
  push:
    tags:
      - '*' # Ejecuta en cualquier nuevo tag
permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5
      
      - run: cd hello_world && opam install dune

      - run: cd hello_world && opam install raylib

      - run: cd hello_world && opam exec -- dune build
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files:
            hello_world/_build/default/bin/*
